# This workflow will deploy two clusters, one in each region, without the workload.
#
# Follow the next steps to use this workflow:
#
# 1. Ensure you have followed the prior sections before deploying this AKS cluster. This way, you will be capable of setting:
#    - the secrets values
#        - AZURE_CREDENTIALS                         The Azure Service Principal that will deploy the AKS cluster in your Azure subscription. For more information please take a look at https://github.com/Azure/login#configure-deployment-credentials
#        - APP_GATEWAY_LISTENER_REGION1_CERTIFICATE_BASE64   The certificate data for app gateway TLS termination. It is base64. Ideally fetch this secret from a platform-managed secret store such as Azure KeyVault: https://github.com/marketplace/actions/azure-key-vault-get-secrets
#        - APP_GATEWAY_LISTENER_REGION2_CERTIFICATE_BASE64   The certificate data for app gateway TLS termination. It is base64. Ideally fetch this secret from a platform-managed secret store such as Azure KeyVault: https://github.com/marketplace/actions/azure-key-vault-get-secrets
#        - AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64 The base 64 encoded AKS Ingress Controller public certificate (as .crt or .cer) to be stored in Azure Key Vault as secret and referenced by Azure Application Gateway as a trusted root certificate.
#    - the cluster parameter
#        -  azuredeploy.parameters.region1.json
#        -  azuredeploy.parameters.region2.json
#
# Take into account the DEPLOY_REGION1 and DEPLOY_REGION2 env variables. If we want to add a new region, the ideal situation is not deploy the already working clusters. Adding a value different of true will skip the specific region steps.
# Changing the cluster stamp file is expected to be applied on all the regions
name: Deploy AKS Secure Baseline clusters stamp and Flux in different regions

on:
  push:
    paths:
      - 'cluster-stamp.json'
      - '.github/workflows/aks-deploy.yaml'
    branches: [ main ]
env:
  DEPLOY_REGION1: 'true'
  DEPLOY_REGION2: 'true'
jobs:
  deploy:
    name: Deploy AKS cluster and Flux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Login into your Azure Subscription using your Azure credentials - make sure the credentials has write permissions for the specific resource group/subscription. The credentials should be stored in GitHub Secrets - (Go to Settings Tab ->Secrets)
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Images
      id: acr-images
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          ACR_NAME_BU0001A0042=$(az deployment group show -g rg-bu0001a0042-shared -n shared-svcs-stamp --query properties.outputs.containerRegistryName.value -o tsv)
          az acr import --source docker.io/library/memcached:1.5.20 -n $ACR_NAME_BU0001A0042 --force
          az acr import --source docker.io/fluxcd/flux:1.19.0 -n $ACR_NAME_BU0001A0042 --force
          az acr import --source docker.io/weaveworks/kured:1.4.0 -n $ACR_NAME_BU0001A0042 --force
          az acr import --source docker.io/library/traefik:2.2.1 -n $ACR_NAME_BU0001A0042 --force

        azcliversion: 2.17.1

    # -----------------------REGION1------------------------------------------------
    # Deploy the cluster into your environment, assuming all prerequisites are up and running.
    - name: Azure CLI - Deploy AKS cluster - Region 1
      id: aks-cluster-region1
      if: success() && env.DEPLOY_REGION1 == 'true'
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
         az group create --name rg-bu0001a0042-03 --location eastus2
         az deployment group create --resource-group rg-bu0001a0042-03 \
            --template-file "cluster-stamp.json" \
             --parameters @azuredeploy.parameters.eastus2.json \
              appGatewayListenerCertificate=${{ secrets.APP_GATEWAY_LISTENER_REGION1_CERTIFICATE_BASE64 }} \
              aksIngressControllerCertificate=${{ secrets.AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64 }}

          echo "::set-output name=name::$(az deployment group show --resource-group rg-bu0001a0042-03 -n cluster-stamp --query properties.outputs.aksClusterName.value -o tsv)"
        azcliversion: 2.17.1

    # Set the AKS cluster context - Region 1
    - name: Set the AKS cluster context - Region 1
      uses: Azure/aks-set-context@v1
      if: success() && env.DEPLOY_REGION1 == 'true'
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ steps.aks-cluster-region1.outputs.name }}
        resource-group: rg-bu0001a0042-03

    # Bake using Kubernetes Kustomize - Region 1
    # NOTE: you could consider using fluxctl action instead. That could help on deploying Flux from a single step instead of baking and then deploying as demonstrated in here.
    - name: Bake manifest - Region 1
      id: aks-kustomize-region1
      if: success() && env.DEPLOY_REGION1 == 'true'
      uses: azure/k8s-bake@v1
      with:
        renderEngine: 'kustomize'
        kustomizationPath: 'cluster-manifests/region1/bootstrapping'
        kubectl-version: 'latest'

    # Create the cluster-baseline-settings namespace and deploy Flux into it - Region 1
    - name: Create the cluster-baseline-settings namespace and deploy Flux - Region 1
      id: aks-deploy-region1
      if: success() && env.DEPLOY_REGION1 == 'true'
      uses: Azure/k8s-deploy@v1
      with:
        namespace: 'cluster-baseline-settings'
        manifests: |
          cluster-manifests/base/cluster-baseline-settings/ns.yaml
          ${{ steps.aks-kustomize-region1.outputs.manifestsBundle }}

    # -----------------------REGION2------------------------------------------------
    # Deploy the cluster into your environment, assuming all prerequisites are up and running.
    - name: Azure CLI - Deploy AKS cluster - Region 2
      id: aks-cluster-region2
      uses: Azure/cli@v1.0.0
      if: success() && env.DEPLOY_REGION2 == 'true'
      with:
        inlineScript: |
         az group create --name rg-bu0001a0042-04 --location centralus
         az deployment group create --resource-group rg-bu0001a0042-04 \
            --template-file "cluster-stamp.json" \
            --parameters @azuredeploy.parameters.centralus.json \
              appGatewayListenerCertificate=${{ secrets.APP_GATEWAY_LISTENER_REGION2_CERTIFICATE_BASE64 }} \
              aksIngressControllerCertificate=${{ secrets.AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64 }}

          echo "::set-output name=name::$(az deployment group show --resource-group rg-bu0001a0042-04 -n cluster-stamp --query properties.outputs.aksClusterName.value -o tsv)"
        azcliversion: 2.17.1

    # Set the AKS cluster context - Region 2
    - name: Set the AKS cluster context - Region 2
      uses: Azure/aks-set-context@v1
      if: success() && env.DEPLOY_REGION2 == 'true'
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ steps.aks-cluster-region2.outputs.name }}
        resource-group: rg-bu0001a0042-04

    # Bake using Kubernetes Kustomize - Region 2
    # NOTE: you could consider using fluxctl action instead. That could help on deploying Flux from a single step instead of baking and then deploying as demonstrated in here.
    - name: Bake manifest - Region 2
      id: aks-kustomize-region2
      uses: azure/k8s-bake@v1
      if: success() && env.DEPLOY_REGION2 == 'true'
      with:
        renderEngine: 'kustomize'
        kustomizationPath: 'cluster-manifests/region2/bootstrapping'
        kubectl-version: 'latest'

    # Create the cluster-baseline-settings namespace and deploy Flux into it - Region 2
    - name: Create the cluster-baseline-settings namespace and deploy Flux - Region 2
      id: aks-deploy-region2
      if: success() && env.DEPLOY_REGION2 == 'true'
      uses: Azure/k8s-deploy@v1
      with:
        namespace: 'cluster-baseline-settings'
        manifests: |
          cluster-manifests/base/cluster-baseline-settings/ns.yaml
          ${{ steps.aks-kustomize-region2.outputs.manifestsBundle }}
