# This file is embedded into the Bicep file.
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8scustomingresstlshostshavedefineddomainsuffix
spec:
  crd:
    spec:
      names:
        kind: k8scustomingresstlshostshavedefineddomainsuffix
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedDomainSuffixes:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8scustomingresstlshostshavedefineddomainsuffix

        violation[{"msg": msg, "details": {}}] {
          allowedDomainSuffixes := input.parameters.allowedDomainSuffixes
          allDefinedHosts := {n | n := input.review.object.spec.tls[_].hosts[_]}
          matchedHosts := { {"host": h, "matchedDomains": d} |
            h := allDefinedHosts[_] ;
            d := { n | n := allowedDomainSuffixes[_] ; endswith(h, n)}
          }
          unmatchedHosts := { h |
            h := matchedHosts[x].host ; 
            d := matchedHosts[x].matchedDomains ; 
            count(d) == 0
          }
          count(unmatchedHosts) > 0
          msg := sprintf("TLS host must have one of defined domain suffixes. Valid domain names are %v; defined TLS hosts are %v; incompliant hosts are %v.", [allowedDomainSuffixes, allDefinedHosts, unmatchedHosts])
        }
