apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- aad-pod-identity.yaml
- akv-secrets-store-csi.yaml
- kured.yaml
- flux.yaml # install this later to prevent from race conditions during the first execution
