# https://raw.githubusercontent.com/Azure/prometheus-collector/refs/heads/main/otelcollector/configmaps/ama-metrics-prometheus-config-configmap.yaml
# This config map can be used to provide Prometheus scrape config for addon replica. Addon runs a singleton replica, and any cluster level services can be discovered and scraped by providing scrape jobs in this configmap.
# https://learn.microsoft.com/azure/virtual-network/kubernetes-network-policies#set-up-for-prometheus-server
kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: "azure-npm-node-metrics"
        metrics_path: /node-metrics
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - source_labels: [__address__]
          action: replace
          regex: ([^:]+)(?::\d+)?
          replacement: "$1:10091"
          target_label: __address__
      - job_name: "azure-npm-cluster-metrics"
        metrics_path: /cluster-metrics
        kubernetes_sd_configs:
        - role: service
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: kube-system
          action: keep
        - source_labels: [__meta_kubernetes_service_name]
          regex: npm-metrics-cluster-service
          action: keep
      # Comment from here to the end to collect advanced metrics: number of entries for each IPSet
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: npm_ipset_counts
          action: drop
    
metadata:
  # ama-metrics-prometheus-config (Recommended) - When a configmap with this name is created, scrape jobs defined in it are run from the Azure monitor metrics replica pod running in the cluster.
  name: ama-metrics-prometheus-config
  namespace: kube-system