apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- aspnetapp.yaml

patchesJson6902:
- target:
    kind: Ingress
    name: aspnetapp-ingress
    version: v1
  path: aspnetapp-ingress-patch.yaml
